import { v4 as uuid } from 'uuid';

const cityNames = [
  { id: uuid(), name: 'Tokyo', sigle: 'TO' },
  { id: uuid(), name: 'London', sigle: 'LN' },
  { id: uuid(), name: 'New_York', sigle: 'NY' },
  { id: uuid(), name: 'Paris', sigle: 'PAR' },
  { id: uuid(), name: 'Singapore', sigle: 'SNGP' },
  { id: uuid(), name: 'Los_Angeles', sigle: 'LA' },
  { id: uuid(), name: 'Boston', sigle: 'BOS' },
  { id: uuid(), name: 'Seoul', sigle: 'SE' },
  { id: uuid(), name: 'San_Francisco', sigle: 'SF' },
  { id: uuid(), name: 'Houston', sigle: 'HOU' },
  { id: uuid(), name: 'Berlin', sigle: 'BER' },
  { id: uuid(), name: 'Chicago', sigle: 'CHI' },
  { id: uuid(), name: 'Stockholm', sigle: 'STK' },
  { id: uuid(), name: 'Dubai', sigle: 'DU' },
  { id: uuid(), name: 'Toronto', sigle: 'TOR' },
  { id: uuid(), name: 'Munich', sigle: 'MUN' },
  { id: uuid(), name: 'Vienna', sigle: 'VIE' },
  { id: uuid(), name: 'Sydney', sigle: 'SYD' },
  { id: uuid(), name: 'Amsterdam', sigle: 'AMTD' },
  { id: uuid(), name: 'Seattle', sigle: 'SEA' },
  { id: uuid(), name: 'Melbourne', sigle: 'MEL' },
  { id: uuid(), name: 'Barcelona', sigle: 'BAR' },
  { id: uuid(), name: 'Beijing', sigle: 'BEI' },
  { id: uuid(), name: 'Copenhagen', sigle: 'CPNG' },
  { id: uuid(), name: 'Oslo', sigle: 'OS' },
  { id: uuid(), name: 'Helsinki', sigle: 'HLSK' },
  { id: uuid(), name: 'Rome', sigle: 'RO' },
  { id: uuid(), name: 'Taipei', sigle: 'TAI' },
  { id: uuid(), name: 'Athens', sigle: 'ATN' },
  { id: uuid(), name: 'Kyoto', sigle: 'KYO' },
  { id: uuid(), name: 'Abu_Dhabi', sigle: 'ADB' },
  { id: uuid(), name: 'Moscow', sigle: 'MOS' },
  { id: uuid(), name: 'Geneva', sigle: 'GEN' },
  { id: uuid(), name: 'Kinshasa', sigle: 'KIN' },
  { id: uuid(), name: 'Mbabane', sigle: 'MBN' },
  { id: uuid(), name: 'Lilongwe', sigle: 'LIL' },
  { id: uuid(), name: 'Johannesburg', sigle: 'JHNB' },
  { id: uuid(), name: 'Kampala', sigle: 'KAM' },
  { id: uuid(), name: 'Tunis', sigle: 'TUN' },
  { id: uuid(), name: 'Cairo', sigle: 'CAI' },
  { id: uuid(), name: 'Brasilia', sigle: 'BRA' },
  { id: uuid(), name: 'Ankara', sigle: 'ANK' },
  { id: uuid(), name: 'Budapest', sigle: 'BDPT' },
];

export default cityNames;
